simple_things_entity_audit_home:
    path: /{page<\d+>?1}
    controller: SimpleThings\EntityAudit\Action\IndexAction

simple_things_entity_audit_viewrevision:
    path: /viewrev/{rev<\d+>}
    controller: SimpleThings\EntityAudit\Action\ViewRevisionAction

simple_things_entity_audit_viewentity_detail:
    path: /viewent/{className}/{id}/{rev<\d+>}
    controller: SimpleThings\EntityAudit\Action\ViewDetailAction

simple_things_entity_audit_viewentity:
    path: /viewent/{className}/{id}
    controller: SimpleThings\EntityAudit\Action\ViewEntityAction

simple_things_entity_audit_compare:
    path: /compare/{className}/{id}/{oldRev?}/{newRev?}
    controller: SimpleThings\EntityAudit\Action\CompareAction
