simple_things_entity_audit_home:
    path: /{page}
    controller: SimpleThings\EntityAudit\Controller\AuditController::index
    defaults:
        page: 1
    requirements:
        page: \d+

simple_things_entity_audit_viewrevision:
    path: /viewrev/{rev}
    controller: SimpleThings\EntityAudit\Controller\AuditController::viewRevision
    requirements:
        rev: \d+

simple_things_entity_audit_viewentity_detail:
    path: /viewent/{className}/{id}/{rev}
    controller: SimpleThings\EntityAudit\Controller\AuditController::viewDetail
    requirements:
        rev: \d+

simple_things_entity_audit_viewentity:
    path: /viewent/{className}/{id}
    controller: SimpleThings\EntityAudit\Controller\AuditController::viewEntity

simple_things_entity_audit_compare:
    path: /compare/{className}/{id}/{oldRev}/{newRev}
    controller: SimpleThings\EntityAudit\Controller\AuditController::compare
    defaults:
        oldRev: ~
        newRev: ~
